version: "2"
services:
  app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - 80:80
   restart: always
   links:
     - db
  db:
    # build:
    #  context: .
    #  dockerfile: Dockerfile-database
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: projet_web_jamendo
      MYSQL_DATABASE_USER: root
      MYSQL_ROOT_PASSWORD: pass
