version: "2"
services:
  app:
   image: kangoula/platystener
   ports:
     - 80:80
   volumes:
     - ./app/:/var/www/html/
   restart: always
   links:
     - database:database
  database:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: jamendo
      MYSQL_DATABASE_USER: root
      MYSQL_ROOT_PASSWORD: pass
