version: "2"
services:
  app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - 80:80  
   container_name: platystener
   restart: always
   links:
       - db:db
  db:
    image: mysql
    container_name: platystener_db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: jamendo 
      MYSQL_ROOT_PASSWORD: pass
